# 模型配置
models:
  deepseek:
    api_base: "https://api.deepseek.com" # 模型服务地址
    available_models:
      - "deepseek-chat"
      - "deepseek-reasoner"
    default_model: "deepseek-chat" # 默认模型
    max_tokens: 8192 # 最大上下文长度
    api_key: "sk-48f1f11bb99c4dfdacb79422f868c07d" # API密钥
  qwen:
    api_base: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    available_models: 
      - "qwen3-max"
      - "qwen3-max-preview"
    default_model: "qwen3-max"
    max_tokens: 65536
    api_key: "sk-35e4cf1aa28545bba88e0f405c140379"
  gpt:
    api_base: "https://yunwu.zeabur.app/v1/"
    available_models:
      - "gpt-5.1"
    default_model: "gpt-5.1"
    max_tokens: 128000
    api_key: "sk-v6wCPxot79WbRzHBt4xJeJsuca418Zx6AIp5dJFfqYvcA6ZW"
  glm:
    api_base: "https://open.bigmodel.cn/api/paas/v4/"
    default_model: "glm-4.6"
    max_tokens: 131072
    api_key: "58d81985b8b843dd861a0f3c34f285d7.1CfANbGSASD0KmzV"
  siliconflow:
    api_base: "https://api.siliconflow.cn/v1/"
    default_model: "deepseek-ai/DeepSeek-V3.2"
    max_tokens: 163840
    api_key: "sk-myhpprlskvczxayqfkpiucnhzixtyhvbpjpaiqfjkbjvugxk"
  google:
    api_base: "https://yunwu.zeabur.app/v1/"
    available_models:
      - "gemini-3-pro-preview"
    default_model: "gemini-3-pro-preview"
    max_tokens: 65536
    api_key: "sk-C8t87XYFNXXIJkR8DuN8GHwnwzyF6SG0HzLG9XAM63MozwLg"


# 项目配置
project:
  default_provider: "qwen" # 项目默认模型提供商
  temerature: 0.1          # 模型温度

# 路径配置
paths:
  data_path: "/home/lwj/data/driver_info" # 保存静态分析内容的路径
  logs_path: "/home/lwj/data/logs"        # 保存日志的路径
  device_code_path: "/home/lwj/data/device_code"  # 保存最终的设备代码的目录
  qemu_hw_fack_pci_path: "/home/lwj/qemu_8.2_linux_6.18/src/qemu-stable-8.2/hw/fake_pci" # qemu项目中保存设备代码的位置
  qemu_run_dir: "/home/lwj/qemu_8.2_linux_6.18/image" # 运行qemu的目录
  driver_name_case_mapping_path: "/home/lwj/data/qemu_config/qemu_config.json" # 驱动名称大小写映射文件
  qemu_kernel_bzImage_path: "/home/lwj/qemu_8.2_linux_6.18/src/linux-6.18-defconfig/arch/x86_64/boot/bzImage" # qemu使用的内核路径
  qemu_image_path: "/home/lwj/qemu_8.2_linux_6.18/image/bullseye.img" # qemu使用的镜像路径
  qemu_log_path: "/home/lwj/qemu_8.2_linux_6.18/qemu.log" # qemu的日志路径
  qemu_out_share_path: "/home/lwj/qemu_8.2_linux_6.18/src/out/share" # qemu的共享目录路径
  qemu_out_shares_path: "/home/lwj/qemu_8.2_linux_6.18/src/out/shares" # qemu的共享目录路径
  qemu-system-x86_64_path: "/home/lwj/qemu_8.2_linux_6.18/src/qemu-stable-8.2/build/qemu-system-x86_64" # qemu-system-x86_64可执行文件路径
  qemu_rum_template_path: "/home/lwj/data/qemu_config/start_qemu_template.sh" # 启动qemu的脚本模板路径
  qemu_build_static_path: "/home/lwj/qemu_8.2_linux_6.18/src/qemu-stable-8.2/build_static" # qemu静态编译路径，用于clangd错误检查
  qemu_build_path: "/home/lwj/qemu_8.2_linux_6.18/src/qemu-stable-8.2/build" # qemu编译路径
  linux_path_prefix: "/home/gkf/桌面/linux_allyesconfig" # 静态分析内容中linux源码路径前缀
  step4_examples_path: "/home/lwj/data/step4_examples"   # 步骤4的修复例子保存路径 
  db_path: "/home/lwj/vdm/driver_info.db"             # 数据库路径  
  qemu_build_sh_path: "/home/lwj/data/qemu_config/build_qemu.sh" # 编译qemu的脚本路径
  id_rsa_path: "/home/lwj/qemu_8.2_linux_6.18/image/bullseye.id_rsa" # 远程登录qemu使用的私钥路径